services:
  app:
    build:
      dockerfile: ./docker/ruby/Dockerfile
      context: ./
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mysql
    ports:
      - 3000:3000

  mysql:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: twilio_recall_db
      TZ: "Asia/Tokyo"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

volumes:
  mysql-data:
